disk: /dev/nvme0n1
home_device: /dev/sdX          # operator fills this in before running
hostname: linux
username: johlan
timezone: Africa/Johannesburg
locale: en_ZA.UTF-8
keymap: us
aur_helper: paru
nvidia_gpu: true
separate_home: true
bridge_interface: enp3s0
vlan_id: 20
data_device: /dev/sdX            # operator fills this in before running
enable_bridge_network: true
enable_virtualization: true
